name: main

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  issues:
    types: [opened, labeled, unlabeled]
  pull_request:
    types: [opened, labeled, unlabeled]
  project_card:
    types: [moved]
  push:
    branches: [develop]
    paths:
      - './SELI-Platform/lib/translation/**'

env:
  GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_ACTION_TOKEN }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job01: 
#    needs: [assign_one_project]
#    if: github.event_name == 'project_card'
#    name: Auto card labeler
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # NOTE @v2 uses the token as an auth http header. Set it to
          # a Personal Access Token instead of secrets.GITHUB_TOKEN
          # so that tag pushes trigger repo push events.
          token: ${{ secrets.MY_PERSONAL_ACTION_TOKEN }}

      # Create or update an issue based on specific file
      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v2.3.1
        #if: github.event_name == 'project_card' && github.event.action == 'moved' 
        with:
          # The GitHub authentication token
          token: ${{ secrets.MY_PERSONAL_ACTION_TOKEN }}
          # The issue number of an existing issue to update
          issue-number: 215
          # The title of the issue.
          title: "Translation Tracker"
          # The file path to the issue content.
          content-filepath: "./SELI-Platform/lib/translation/english.js"
          # A comma separated list of labels.
          labels: "automated :robot:, type:l10n"
          # A comma separated list of assignees (GitHub usernames).
          assignees: "ozguryasar, armagan9706, caroltaus"
          # The name of the project for which a card should be created.
          #project: # optional
          # The name of the project column under which a card should be created.
          #project-column: # optional

      - uses: technote-space/auto-card-labeler@v1 
        #GitHub actions that automatically labels Issues or PullRequests based on project card moves
        if: github.event_name == 'push'
        with:
          GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_ACTION_TOKEN }}
            # Config file name.
            #CONFIG_FILENAME: # default is card-labeler.yml

      - name: commenter by label
       #Label triggered GitHub Actions for posting a template message, automatically close or reopen issues or pull requests
        uses: peaceiris/actions-label-commenter@v1.3.2 
        if: |
          (github.event_name == 'issues' || github.event_name == 'project_card') && 
          (github.event.action == 'labeled' || github.event.action == 'unlabeled')
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           config_file: .github/label-commenter-config.yml

      - name: Assign 'FEATURE REQUEST' to 'TRIAGE - FEATURE REQUEST'
        uses: srggrs/assign-one-project-github-action@1.2.0
        if: |
          github.event_name == 'issues' && 
          github.event.action == 'labeled' &&  
          contains(github.event.issue.labels.*.name, 'Feature Request :bulb:')
        with:
          project: 'https://github.com/solex2006/SELIProject/projects/6'
          column_name: 'NEEDS TRIAGE'
          
      - name: Assign 'bug' label to 'TRIAGE - Bugs'
        uses: srggrs/assign-one-project-github-action@1.2.0
        if: |
          github.event_name == 'issues' && 
          github.event.action == 'labeled' &&
          contains(github.event.issue.labels.*.name, ':bug:bug')
        with:
          project: 'https://github.com/solex2006/SELIProject/projects/7'
          column_name: 'NEEDS TRIAGE'
        
      - name: Assign '1 - PLANNING' label to 'FEATURE SPECIFICATION'
        uses: srggrs/assign-one-project-github-action@1.2.0
        if: |
          github.event_name == 'issues' && 
          github.event.action == 'labeled' &&  (
          contains(github.event.issue.labels.*.name, '1 - Planning') ||
          contains(github.event.issue.labels.*.name, 'need specification'))
        with:
          project: 'https://github.com/solex2006/SELIProject/projects/8'
          column_name: 'PENDING FEATURE REQUEST'

      - name: Assign '2 - READY' label to 'DEVELOPMENT CYCLE - TO-DO'
        uses: srggrs/assign-one-project-github-action@1.2.0
        if: |
          github.event_name == 'issues' && 
          github.event.action == 'labeled' &&  
          contains(github.event.issue.labels.*.name, '2 - Ready') &&
          ( contains(github.event.issue.labels.*.name, 'Feature Specification') ||
          contains(github.event.issue.labels.*.name, 'Feature Story'))  
        with:
          project: 'https://github.com/solex2006/SELIProject/projects/9'
          column_name: 'TO-DO'
      
      - name: Assign 'need tester' label to 'FUNCTIONALITY TEST CYCLE'
        uses: srggrs/assign-one-project-github-action@1.2.0
        if: |
          github.event_name == 'issues' && 
          github.event.action == 'labeled' &&  
          contains(github.event.issue.labels.*.name, 'need tester')
        with:
          project: 'https://github.com/solex2006/SELIProject/projects/10'
          column_name: 'TO-DO'
